//IMPORT JAVA.UTIL.RANDOM;
import java.util.*;

public class random_numbers {
    public static void main(String[] args) {
        
        Random rand =  new Random();
        //numbers generated are not random but are psuedo-random they are generated through a PRGN.
        //In Java, a pseudo-random number is a number that appears random, but is actually generated using a deterministic algorithm. This means that if you know the seed value and algorithm used, you can predict the sequence of numbers generated.
        //Random numbers are called psuedo-random numbers when they are generated by some deterministic process but they qualify the predetermined statistical test for randomness

        int x = rand.nextInt(7);
        //this will generate random integer values from 0-6 for x

        System.out.println();
        System.out.println("x is: " + x);

        double y = rand.nextDouble(1,3);
        System.out.println();
        System.out.println("y is: " + y);

        boolean z = rand.nextBoolean();
        System.out.println();
        System.out.println("z is: " + z); 



    }
    
}
